Tools: Use monkey's init script that actually works...
Signed-off-by: matematik7 <domen.ipavec@z-v.si>

diff --git a/tools/monkey.init b/tools/monkey.init
--- a/tools/monkey.init
+++ b/tools/monkey.init
@@ -12,146 +12,93 @@
 ### END INIT INFO
 
 # Author: Domen Ipavec <domen.ipavec@z-v.si>
-#
-# Do NOT "set -e"
 
-# PATH should only include /usr/* if it runs after the mountnfs.sh script
-PATH=/sbin:/usr/sbin:/bin:/usr/bin
-DESC="Start Monkey HTTP Daemon"
-NAME=monkey
-DAEMON=/home/pi/.dudac/stage/monkey/bin/$NAME
-DAEMON_ARGS=""
-PIDFILE=/var/run/$NAME.pid
-SCRIPTNAME=/etc/init.d/$NAME
+# Change this if necessary
+DUDACPATH=/home/pi/.dudac
+# End change
 
-# Exit if the package is not installed
-[ -x "$DAEMON" ] || exit 0
+CONFDIR=$DUDACPATH/stage/monkey/conf
+BINMONKEY=$DUDACPATH/stage/monkey/bin/monkey
 
-# Read configuration variable file if it is present
-[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+PORT=$(sed -n '/^[ \t]*Port/s/^.* //p' "$CONFDIR/monkey.conf")
+PIDFILE=$(sed -n '/^[ \t]*PidFile/s/^.* //p' "$CONFDIR/monkey.conf")."$PORT"
 
-# Load the VERBOSE setting and other rcS variables
-. /lib/init/vars.sh
-
-# Define LSB log_* functions.
-# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
-# and status_of_proc is working.
-. /lib/lsb/init-functions
-
-#
-# Function that starts the daemon/service
-#
-do_start()
-{
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
-		$DAEMON_ARGS \
-		|| return 2
-	# Add code here, if necessary, that waits for the process to be ready
-	# to handle requests from services started subsequently which depend
-	# on this one.  As a last resort, sleep for some time.
-}
-
-#
-# Function that stops the daemon/service
-#
-do_stop()
-{
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
-	RETVAL="$?"
-	[ "$RETVAL" = 2 ] && return 2
-	# Wait for children to finish too if this is a daemon that forks
-	# and if the daemon is only ever run from this initscript.
-	# If the above conditions are not satisfied then add some other code
-	# that waits for the process to drop all resources that could be
-	# needed by services started subsequently.  A last resort is to
-	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
-	[ "$?" = 2 ] && return 2
-	# Many daemons don't delete their pidfiles when they exit.
-	rm -f $PIDFILE
-	return "$RETVAL"
-}
-
-#
-# Function that sends a SIGHUP to the daemon/service
-#
-do_reload() {
-	#
-	# If the daemon can reload its configuration without
-	# restarting (for example, when it is sent a SIGHUP),
-	# then implement that here.
-	#
-	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
-	return 0
-}
-
-case "$1" in
-  start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-	do_start
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+for arg in $*; do
+	case "$arg" in
+		-*=*) optarg=`echo "$arg" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
+		   *) optarg= ;;
 	esac
-	;;
-  stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-	do_stop
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
-	;;
-  status)
-	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-	;;
-  #reload|force-reload)
-	#
-	# If do_reload() is not implemented then leave this commented out
-	# and leave 'force-reload' as an alias for 'restart'.
-	#
-	#log_daemon_msg "Reloading $DESC" "$NAME"
-	#do_reload
-	#log_end_msg $?
-	#;;
-  restart|force-reload)
-	#
-	# If the "reload" option is implemented then remove the
-	# 'force-reload' alias
-	#
-	log_daemon_msg "Restarting $DESC" "$NAME"
-	do_stop
-	case "$?" in
-	  0|1)
-		do_start
-		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
-		esac
+
+	if  ! test -f $PIDFILE ; then
+		STATUS="no"
+	else
+		PIDMONKEY=`cat $PIDFILE`
+		if ! kill -0 $PIDMONKEY 2>/dev/null; then
+			STATUS="no"
+		else
+			STATUS="yes"
+		fi
+	fi
+
+	case "$arg" in
+		start)
+			if [ "$STATUS" = "yes"  ] ; then
+				echo "Monkey is running... (PID=$PIDMONKEY)"
+				exit 1
+			fi
+			if ! test -x $BINMONKEY ; then
+				echo "Error: I can't run binary file"
+				exit 1
+			else
+				if $BINMONKEY --daemon  2>/dev/null ; then
+					echo "Running Monkey -> OK"
+					exit 0
+				fi
+			fi
 		;;
-	  *)
-		# Failed to stop
-		log_end_msg 1
+		stop)
+			if  [ "$STATUS" = "no" ]; then
+				echo "Monkey is not running."
+				exit 0
+			fi
+			kill -9 $PIDMONKEY
+			rm -rf $PIDFILE > /dev/null
+			echo "Monkey stopped ($PIDMONKEY)"
+			exit 0
+			;;
+		force-reload|restart)
+			if  [ "$STATUS" = "yes" ]; then
+				if ! kill $PIDMONKEY  > /dev/null ; then
+					killall -9 monkey
+				else
+					echo -n "Stopping Monkey... "
+				fi
+			else
+				echo -n "Monkey is not running... "
+			fi
+			if ! test -x $BINMONKEY ; then
+				echo "Error: I can't run binary file"
+				exit 1
+			else
+				$BINMONKEY --daemon > /dev/null
+				echo "Restarting -> OK"
+				exit 0
+			fi
+			;;
+		status)
+                        if  [ "$STATUS" = "yes" ]; then
+				echo "Monkey is running... (PID=$PIDMONKEY)"
+			else
+                                echo "Monkey is not running... "
+                        fi
+			exit 0
+			;;
+		*)
+			echo "Usage : monkey [start|stop|restart|status|help]"
+			exit 1
 		;;
 	esac
-	;;
-  *)
-	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
-	exit 3
-	;;
-esac
+done
+echo "Usage : monkey [start|stop|restart|status|help]"
 
-:
+exit 0
